---
# Project Information
site_name: {{ cookiecutter.project_name }}
site_author: {{ cookiecutter.full_name }}
site_description: {{ cookiecutter.project_short_description }}

# Repository information
repo_name: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 {{ cookiecutter.full_name }}

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.github_username }}
      name: {{ cookiecutter.github_username }} on GitHub

# Page tree
nav:
  - Home: index.md
